baseURL = "https://roothunt3rs.github.io/website/"
languageCode = "en"
title = "RootHunt3rs CTF Team"
theme = "blowfish"

enableRobotsTXT = true
relativeURLs = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  colorScheme = "dark"
  defaultAppearance = "dark"
  enableSearch = true
  enableCodeCopy = true

